# Generated by Django 5.0.4 on 2024-07-23 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backendstaff_name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_city', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Gurantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gurantee', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=2)),
                ('gstin_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_phone', models.CharField(max_length=10)),
                ('person_email', models.EmailField(max_length=100)),
                ('person_city', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.companytable')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(default='Test', max_length=150)),
                ('bio', models.TextField(null=True)),
                ('email', models.CharField(blank=True, default='a@gmail.com', max_length=200)),
                ('phone', models.CharField(blank=True, default=123, max_length=10)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.state')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.sublocation')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ArivalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateField()),
                ('origin_date', models.DateField()),
                ('arival_date', models.DateField()),
                ('depart_date', models.DateField()),
                ('file_Ref', models.CharField(blank=True, max_length=100, null=True)),
                ('ground_partner_file_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_pax_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_pax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('adt_pax', models.CharField(blank=True, max_length=100, null=True)),
                ('child_pax', models.CharField(blank=True, max_length=100, null=True)),
                ('adt_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('child_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('nights', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_check_by', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_num', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_date', models.DateField()),
                ('inv_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('folder_link', models.CharField(blank=True, max_length=100, null=True)),
                ('part_pmt_amt', models.CharField(blank=True, max_length=100, null=True)),
                ('final_pmt_amt', models.CharField(blank=True, max_length=100, null=True)),
                ('final_pmt_deadline', models.DateField()),
                ('payment_india', models.CharField(blank=True, max_length=100, null=True)),
                ('itinerary_submit_date', models.DateField()),
                ('purchase_amt', models.CharField(blank=True, max_length=100, null=True)),
                ('markup_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_letter_submit_date', models.DateField()),
                ('voucher_submit_date', models.DateField()),
                ('agency_staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_staff_email', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_staff_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('package_details', models.CharField(blank=True, max_length=100, null=True)),
                ('cdmc_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('ground_partner_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('backend_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.backendstaff')),
                ('agency_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.companytable')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.currency')),
                ('gurantee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.gurantee')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.location')),
                ('payment_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.paymentstatus')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.staff')),
                ('sub_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.sublocation')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
