# Generated by Django 5.0.4 on 2024-10-15 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliations', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='CategoryClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_clients', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_area', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='OfficeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_role', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.staffdetails'),
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='arivaltable',
            name='final_pmt_amt',
        ),
        migrations.RemoveField(
            model_name='arivaltable',
            name='part_pmt_amt',
        ),
        migrations.RemoveField(
            model_name='contacttable',
            name='person_city',
        ),
        migrations.AddField(
            model_name='arivaltable',
            name='amt_recev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arivaltable',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arivalcreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arivaltable',
            name='currency_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arivaltable',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arivaleditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_card',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_local_area1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_local_area2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_pincode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.state'),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactcreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacteditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='job',
            field=models.CharField(blank=True, default='staff', max_length=255),
        ),
        migrations.AddField(
            model_name='state',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='adt_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='adt_pax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='child_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='child_pax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='final_pmt_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='gurantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.gurantee'),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='inv_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='inv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='itinerary_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='nights',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='purchase_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='visa_letter_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='voucher_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='cat_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.categoryclients'),
        ),
        migrations.CreateModel(
            name='CompanyKYCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_branch', models.CharField(max_length=150)),
                ('Constitution', models.CharField(max_length=255)),
                ('pancard_no', models.CharField(max_length=255)),
                ('pancard_file', models.ImageField(default='file.png', null=True, upload_to='')),
                ('gstin', models.CharField(max_length=255)),
                ('gstin_file', models.ImageField(default='file.png', null=True, upload_to='')),
                ('msme_no', models.CharField(max_length=255)),
                ('msme_file', models.ImageField(default='file.png', null=True, upload_to='')),
                ('company_reg_address', models.CharField(max_length=255)),
                ('company_city', models.CharField(max_length=255)),
                ('company_pincode', models.CharField(max_length=255)),
                ('company_email', models.CharField(max_length=255)),
                ('company_landline', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company_Affiliations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.affiliations')),
                ('company_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.state')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='agency_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.companykycdetails'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('suport_file', models.ImageField(blank=True, default='file.png', upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbackcreator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbackeditor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contacttable',
            name='focus_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.focusarea'),
        ),
        migrations.CreateModel(
            name='NewCompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=16, null=True)),
                ('company_address', models.CharField(max_length=200)),
                ('company_city', models.CharField(blank=True, max_length=100)),
                ('company_pincode', models.CharField(blank=True, max_length=6)),
                ('person_name', models.CharField(max_length=200)),
                ('person_phone', models.CharField(max_length=10)),
                ('person_email', models.EmailField(max_length=100)),
                ('person_designation', models.CharField(max_length=200)),
                ('kyc_status', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.state')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcreator', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='company_kyc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.newcompanyregistration'),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.newcompanyregistration'),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='office_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.officerole'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='CompanyTable',
        ),
    ]
