# Generated by Django 5.0.4 on 2024-07-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_state_options_state_created_state_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='job',
            field=models.CharField(blank=True, default='staff', max_length=255),
        ),
    ]
