# Generated by Django 5.0.4 on 2024-10-16 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_affiliations_categoryclients_focusarea_officerole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companykycdetails',
            name='cat_client',
            field=models.ManyToManyField(blank=True, to='crm.categoryclients'),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='focus_area',
            field=models.ManyToManyField(blank=True, to='crm.focusarea'),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='introduced_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='productivity_previous',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='productivity_second_previous',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='relationship_manager',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='team_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='adt_pax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='child_pax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='file_Ref',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='nights',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='sub_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.sublocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='msme_file',
            field=models.ImageField(blank=True, default='file.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='msme_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='cat_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.categoryclients'),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.newcompanyregistration'),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='contact_card',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='contact_city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='contact_local_area1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='contact_pincode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='contact_state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='focus_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.focusarea'),
        ),
        migrations.AlterField(
            model_name='newcompanyregistration',
            name='company_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newcompanyregistration',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newcompanyregistration',
            name='company_pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='newcompanyregistration',
            name='gst_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='job',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='user_full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
