# Generated by Django 5.0.4 on 2024-07-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_staffdetails_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('company_address', models.CharField(max_length=200)),
                ('company_city', models.CharField(blank=True, max_length=100)),
                ('company_pincode', models.CharField(blank=True, max_length=6)),
                ('person_name', models.CharField(max_length=200)),
                ('person_phone', models.CharField(max_length=10)),
                ('person_email', models.EmailField(max_length=100)),
                ('person_designation', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.state')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
