# Generated by Django 5.0.4 on 2024-10-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_companykycdetails_cat_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttable',
            name='cat_client',
        ),
        migrations.RemoveField(
            model_name='contacttable',
            name='focus_area',
        ),
        migrations.AddField(
            model_name='contacttable',
            name='cat_client',
            field=models.ManyToManyField(blank=True, to='crm.categoryclients'),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='focus_area',
            field=models.ManyToManyField(blank=True, to='crm.focusarea'),
        ),
    ]
