# Generated by Django 5.0.4 on 2024-10-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contacttable_anniversary_contacttable_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('person_name', models.CharField(max_length=200)),
                ('contact_designation', models.CharField(max_length=255)),
                ('person_phone', models.CharField(max_length=10)),
                ('person_email', models.EmailField(max_length=100)),
                ('contact_local_area1', models.CharField(max_length=255)),
                ('contact_local_area2', models.CharField(blank=True, max_length=255)),
                ('contact_city', models.CharField(max_length=255)),
                ('contact_pincode', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=225)),
                ('dob', models.DateField(blank=True)),
                ('anniversary', models.DateField(blank=True)),
                ('contact_card', models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cat_client', models.ManyToManyField(blank=True, to='crm.categoryclients')),
                ('contact_state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.state')),
                ('focus_area', models.ManyToManyField(blank=True, to='crm.focusarea')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
