# Generated by Django 5.0.4 on 2024-07-24 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_newcompanyregistration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFullKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='agency_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.companyfullkyc'),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.companyfullkyc'),
        ),
        migrations.CreateModel(
            name='CompanyKYCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_branch', models.CharField(max_length=150)),
                ('company_name_code', models.CharField(editable=False, max_length=255)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.companyfullkyc')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyTable',
        ),
    ]
