# Generated by Django 5.0.4 on 2024-10-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_individualcontacttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualcontacttable',
            name='anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualcontacttable',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
