# Generated by Django 5.0.4 on 2024-07-24 13:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_companyfullkyc_alter_arivaltable_agency_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliations', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='companykycdetails',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='Constitution',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='company_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='company_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='company_landline',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='company_pincode',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='company_reg_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='company_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.state'),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='gstin',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='gstin_file',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='msme_file',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='msme_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='pancard_file',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='pancard_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='company_Affiliations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.affiliations'),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='office_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.officerole'),
        ),
    ]
