# Generated by Django 5.1 on 2024-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_individualcontacttable_anniversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykycdetails',
            name='productivity_previous',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='productivity_second_previous',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacttable',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
