# Generated by Django 5.0.4 on 2024-07-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_companykycdetails_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companykycdetails',
            old_name='company_name',
            new_name='company_kyc',
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='company_name_code',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
