# Generated by Django 5.0.4 on 2024-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rename_company_name_companykycdetails_company_kyc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykycdetails',
            name='company_name_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
