# Generated by Django 5.0.4 on 2024-07-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_companykycdetails_company_name_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykycdetails',
            name='company_kyc',
            field=models.ForeignKey(default='Deleted Company', on_delete=django.db.models.deletion.SET_DEFAULT, to='crm.companyfullkyc'),
        ),
    ]
