# Generated by Django 5.0.4 on 2024-07-29 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_companykycdetails_company_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykycdetails',
            name='company_kyc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.companyfullkyc'),
        ),
    ]
