# Generated by Django 5.0.4 on 2024-07-29 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_companykycdetails_company_kyc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companykycdetails',
            name='company_name_code',
        ),
        migrations.RemoveField(
            model_name='companykycdetails',
            name='username',
        ),
        migrations.RemoveField(
            model_name='newcompanyregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companykycdetails',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newcompanyregistration',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newcreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newcompanyregistration',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='gstin_file',
            field=models.ImageField(default='Mini_Flower.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='msme_file',
            field=models.ImageField(default='Mini_Flower.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='pancard_file',
            field=models.ImageField(default='Mini_Flower.png', null=True, upload_to=''),
        ),
    ]
