# Generated by Django 5.0.4 on 2024-07-30 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_companykycdetails_company_name_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttable',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactcreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacteditor', to=settings.AUTH_USER_MODEL),
        ),
    ]
