# Generated by Django 5.0.4 on 2024-07-30 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_contacttable_creator_contacttable_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_clients', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_area', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.RemoveField(
            model_name='contacttable',
            name='person_city',
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_local_area1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_local_area2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_pincode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='contact_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.state'),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='cat_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.categoryclients'),
        ),
        migrations.AddField(
            model_name='contacttable',
            name='focus_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.focusarea'),
        ),
    ]
