# Generated by Django 5.0.4 on 2024-07-30 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_categoryclients_focusarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttable',
            name='contact_designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
