# Generated by Django 5.0.4 on 2024-07-31 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_arivaltable_final_pmt_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arivaltable',
            name='part_pmt_deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
