# Generated by Django 5.0.4 on 2024-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_arivaltable_part_pmt_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arivaltable',
            name='final_pmt_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='inv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='itinerary_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='visa_letter_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='voucher_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
