# Generated by Django 5.0.4 on 2024-08-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_arivaltable_part_pmt_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcompanyregistration',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newcompany', to='crm.companyfullkyc'),
        ),
    ]
