# Generated by Django 5.0.4 on 2024-08-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_newcompanyregistration_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttable',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.companyfullkyc'),
        ),
    ]
