# Generated by Django 5.0.4 on 2024-08-03 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_contacttable_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliations',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='officerole',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='affiliations',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliations',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='officerole',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officerole',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
