# Generated by Django 5.1 on 2024-09-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_feedback_created_feedback_creator_feedback_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to=''),
        ),
    ]
