# Generated by Django 5.1 on 2024-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_alter_staffdetails_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
