# Generated by Django 5.1 on 2024-09-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_contacttable_contact_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttable',
            name='contact_card',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to=''),
        ),
    ]
