# Generated by Django 5.1 on 2024-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_alter_contacttable_contact_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttable',
            name='contact_card',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
