# Generated by Django 5.1 on 2024-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_alter_contacttable_contact_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykycdetails',
            name='gstin_file',
            field=models.ImageField(default='file.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='msme_file',
            field=models.ImageField(default='file.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companykycdetails',
            name='pancard_file',
            field=models.ImageField(default='file.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suport_file',
            field=models.ImageField(blank=True, default='file.png', upload_to=''),
        ),
    ]
