# Generated by Django 5.1 on 2024-09-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_alter_companykycdetails_gstin_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arivaltable',
            name='agency_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.companykycdetails'),
        ),
    ]
