# Generated by Django 5.1 on 2024-09-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_arivaltable_currency_rate_companyfullkyc_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
