# Generated by Django 5.1 on 2024-09-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttable',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.companyfullkyc'),
        ),
    ]
