# Generated by Django 5.1 on 2024-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_rename_final_pmt_amt_arivaltable_amt_recev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arivaltable',
            name='currency_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
