# Generated by Django 5.1 on 2024-09-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_alter_arivaltable_currency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arivaltable',
            name='adt_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='adt_pax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='child_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='child_pax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='inv_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='nights',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arivaltable',
            name='purchase_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
