# Generated by Django 5.1 on 2024-09-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_alter_arivaltable_adt_cost_alter_arivaltable_adt_pax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arivaltable',
            name='amt_recev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
